export const countryMeta = {
    AL: { name: "Albania", flag: "https://flagcdn.com/w40/al.png" },
    AD: { name: "Andorra", flag: "https://flagcdn.com/w40/ad.png" },
    AM: { name: "Armenia", flag: "https://flagcdn.com/w40/am.png" },
    AT: { name: "Austria", flag: "https://flagcdn.com/w40/at.png" },
    AZ: { name: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png" },
    BY: { name: "Belarus", flag: "https://flagcdn.com/w40/by.png" },
    BE: { name: "Belgium", flag: "https://flagcdn.com/w40/be.png" },
    BA: { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w40/ba.png" },
    BG: { name: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png" },
    HR: { name: "Croatia", flag: "https://flagcdn.com/w40/hr.png" },
    CY: { name: "Cyprus", flag: "https://flagcdn.com/w40/cy.png" },
    CZ: { name: "Czechia", flag: "https://flagcdn.com/w40/cz.png" },
    DK: { name: "Denmark", flag: "https://flagcdn.com/w40/dk.png" },
    EE: { name: "Estonia", flag: "https://flagcdn.com/w40/ee.png" },
    FI: { name: "Finland", flag: "https://flagcdn.com/w40/fi.png" },
    FR: { name: "France", flag: "https://flagcdn.com/w40/fr.png" },
    GE: { name: "Georgia", flag: "https://flagcdn.com/w40/ge.png" },
    DE: { name: "Germany", flag: "https://flagcdn.com/w40/de.png" },
    GR: { name: "Greece", flag: "https://flagcdn.com/w40/gr.png" },
    HU: { name: "Hungary", flag: "https://flagcdn.com/w40/hu.png" },
    IS: { name: "Iceland", flag: "https://flagcdn.com/w40/is.png" },
    IE: { name: "Ireland", flag: "https://flagcdn.com/w40/ie.png" },
    IT: { name: "Italy", flag: "https://flagcdn.com/w40/it.png" },
    KZ: { name: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png" },
    XK: { name: "Kosovo", flag: "https://flagcdn.com/w40/xk.png" },
    LV: { name: "Latvia", flag: "https://flagcdn.com/w40/lv.png" },
    LI: { name: "Liechtenstein", flag: "https://flagcdn.com/w40/li.png" },
    LT: { name: "Lithuania", flag: "https://flagcdn.com/w40/lt.png" },
    LU: { name: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png" },
    MT: { name: "Malta", flag: "https://flagcdn.com/w40/mt.png" },
    MD: { name: "Moldova", flag: "https://flagcdn.com/w40/md.png" },
    MC: { name: "Monaco", flag: "https://flagcdn.com/w40/mc.png" },
    ME: { name: "Montenegro", flag: "https://flagcdn.com/w40/me.png" },
    NL: { name: "Netherlands", flag: "https://flagcdn.com/w40/nl.png" },
    MK: { name: "North Macedonia", flag: "https://flagcdn.com/w40/mk.png" },
    NO: { name: "Norway", flag: "https://flagcdn.com/w40/no.png" },
    PL: { name: "Poland", flag: "https://flagcdn.com/w40/pl.png" },
    PT: { name: "Portugal", flag: "https://flagcdn.com/w40/pt.png" },
    RO: { name: "Romania", flag: "https://flagcdn.com/w40/ro.png" },
    RU: { name: "Russia", flag: "https://flagcdn.com/w40/ru.png" },
    SM: { name: "San Marino", flag: "https://flagcdn.com/w40/sm.png" },
    RS: { name: "Serbia", flag: "https://flagcdn.com/w40/rs.png" },
    SK: { name: "Slovakia", flag: "https://flagcdn.com/w40/sk.png" },
    SI: { name: "Slovenia", flag: "https://flagcdn.com/w40/si.png" },
    ES: { name: "Spain", flag: "https://flagcdn.com/w40/es.png" },
    SE: { name: "Sweden", flag: "https://flagcdn.com/w40/se.png" },
    CH: { name: "Switzerland", flag: "https://flagcdn.com/w40/ch.png" },
    TR: { name: "Turkey", flag: "https://flagcdn.com/w40/tr.png" },
    UA: { name: "Ukraine", flag: "https://flagcdn.com/w40/ua.png" },
    GB: { name: "United Kingdom", flag: "https://flagcdn.com/w40/gb.png" },
    VA: { name: "Vatican City", flag: "https://flagcdn.com/w40/va.png" }
  };
  