name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # --- Build Main Version ---
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js (main)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (main)
        run: npm ci

      - name: Remove old build
        run: rm -rf dist

      - name: Build main version (root deploy)
        run: VITE_BASE_PATH=/alpenchallenge/ npm run build

      # --- Build streamlayer Branch Version ---
      - name: Checkout streamlayer branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: streamlayer
          path: streamlayer

      - name: Setup Node.js (streamlayer)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (streamlayer)
        working-directory: streamlayer
        run: npm ci

      - name: Build streamlayer branch version
        working-directory: streamlayer
        run: VITE_BASE_PATH=/alpenchallenge/streamlayer/ npm run build

      - name: Copy streamlayer build into main dist
        run: |
          mkdir -p dist/streamlayer
          cp -r streamlayer/dist/* dist/streamlayer/

      # --- Build static Branch Version ---
      - name: Checkout static branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: static
          path: static

      - name: Setup Node.js (static)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (static)
        working-directory: static
        run: npm ci

      - name: Build static branch version
        working-directory: static
        run: VITE_BASE_PATH=/alpenchallenge/static/ npm run build

      - name: Copy static build into main dist
        run: |
          mkdir -p dist/static
          cp -r static/dist/* dist/static/

      - name: Remove unnecessary files
        run: find dist -type l -delete

      - name: Check size of dist
        run: du -sh dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
